---

- name: Test if SSH is possible
  command: echo success
  register: echo_output
  
- debug:
    msg: "{{ echo_output.stdout }}"

- name: Disable existing Wireguard connection to APT works
  command: ifdown wg0

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'

- name: Set hostname for wireguard client
  hostname:
    name: "{{ ansible_host }}"
    use: systemd

- name: Update repositories and all packages on client
  apt:
    name: "*"
    update_cache: yes
    state: latest

- name: Install necessary utils on wireguard client
  apt:
    pkg:
     - screen
     - rsync
     - lshw
     - man-db
     - ethtool
     - gddrescue
     - fio
     - fping
     - sysstat
     - dstat
     - bpfcc-tools
     - tshark
     - netcat
     - socat
     - wireguard
     - ufw

- name: Allow all access to TCP port 22 for SSH
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow all access to TCP port 139 for smbd
  ufw:
    rule: allow
    port: '139'
    proto: tcp

- name: Allow all access to TCP port 445 for smbd
  ufw:
    rule: allow
    port: '445'
    proto: tcp

- name: Allow all access to UDP port 137 for nmbd
  ufw:
    rule: allow
    port: '137'
    proto: udp

- name: Allow all access to UDP port 138 for nmbd
  ufw:
    rule: allow
    port: '138'
    proto: udp

# https://newbedev.com/how-to-enable-ufw-firewall-to-allow-icmp-response
- name: Allow ICMP responses for ping
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
    marker_begin: "ping BEGIN"
    marker_end: "ping END"
    block: |
      # allow ICMP requests with UFW
      -A ufw-before-output -p icmp -j ACCEPT

- name: Setup UFW before rules
  blockinfile:
    path: /etc/ufw/before.rules
    marker_begin: "forwarding BEGIN"
    marker_end: "forwarding END"
    block: |
      # nat Table rules
      *nat
      :PREROUTING ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]
      
      # flush any previous NAT rules
      -F
      
      # Port Forwardings
      -A PREROUTING -i eth0 -p tcp --dport 2222 -j DNAT --to-destination 192.168.99.1
      -A PREROUTING -i eth0 -p tcp --dport 139 -j DNAT --to-destination 192.168.99.1
      -A PREROUTING -i eth0 -p tcp --dport 445 -j DNAT --to-destination 192.168.99.1
      -A PREROUTING -i eth0 -p udp --dport 137 -j DNAT --to-destination 192.168.99.1
      -A PREROUTING -i eth0 -p udp --dport 138 -j DNAT --to-destination 192.168.99.1
      
      # Forward traffic from wg0 through eth0.
      -A POSTROUTING -s 192.168.1.0/24 -o wg0 -j MASQUERADE
      #-A POSTROUTING -o wg0 -j MASQUERADE
      
      # don't delete the 'COMMIT' line or these nat table rules won't be processed
      COMMIT

- name: Default allow outgoing traffic with UFW
  ufw:
    policy: allow
    direction: outgoing

- name: Default deny incoming traffic with UFW
  ufw:
    policy: allow
    direction: incoming

- name: Default allow forwarding traffic with UFW
  ufw:
    policy: allow
    route: yes
    direction: routed

- name: Reload UFW
  ufw:
    state: reloaded
