

#9) If base domain isn't used (if matrix_nginx_proxy_base_domain_serving_enabled: true) then run the 'Configure Website + Access Export' job template again to enable the base domain site.

# aveng.xyz - 1 - Configure Website + Access Export

- name: Include matrix_vars.yml variable file
  include_vars: "/tmp/{{ matrix_domain }}-matrix_vars.yml"

- name: Collect the extra_vars.json of the new subscription. 
  delegate_to: "{{ awx_server }}"
  fetch:
    src: "/var/lib/awx/projects/clients/{{ member_id }}/{{ new_subscription_id }}/extra_vars.json"
    dest: "/tmp/{{ matrix_domain }}-new_extra_vars.json"
    flat: yes

- name: Launch configure website job template on AWX
  awx.awx.tower_job_launch:
    job_template: "{{ matrix_domain }} - 1 - Configure Website + Access Export"
    extra_vars: "{{ lookup('file', '/tmp/{{ matrix_domain }}-new_extra_vars.json') }}"
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: matrix_nginx_proxy_base_domain_serving_enabled | bool
  register: configure_website_job

- name: Wait for job max 900s (15m)
  awx.awx.tower_job_wait:
    job_id: "{{ configure_website_job.id }}"
    timeout: 900
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: matrix_nginx_proxy_base_domain_serving_enabled | bool
