


- name: Include 'new_subscription_id' variables from '{{ matrix_domain }}.yml'
  include_vars:
    file: './inventory/{{ matrix_domain }}.yml'
  when: matrix_domain_file.stat.exists


#16) Remove the 'imposter-check' tag again and run 'Provision a New Server' again to load up the surveys from matrix_vars.yml


- name: Save new 'Provision Server' survey.json to the AWX tower, template
  template:
    src: './surveys/provision_survey_digitalocean.json.j2'
    dest: '/tmp/{{ matrix_domain }}_provision_survey_digitalocean.json'
  when: subscription_type == "digitalocean"

- name: Save new 'Provision Server' survey.json to the AWX tower, template
  template:
    src: './surveys/provision_survey_on-premises.json.j2'
    dest: '/tmp/{{ matrix_domain }}_provision_survey_on-premises.json'
  when: subscription_type == "on_premises"

- name: Launch provision job template again on AWX to regenerate the deleted templates
  awx.awx.tower_job_launch:
    job_template: "0 - {{ new_subscription_id }} - Provision a New Server"
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  register: provision_job

- name: Wait for provision job max 900s (15m)
  awx.awx.tower_job_wait:
    job_id: "{{ provision_job.id }}"
    timeout: 900
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

