
#17) Copy the DNS information and send it to the customer so they can configure DNS again. For Example:

#        "Your server has been created! You now need to configure your DNS to have the",
#        "following records:",
#        "Type    Host                    Priority  Weight  Port   Target",
#        "A       -                       -         -       -      178.62.95.215",
#        "A       -                       -         -       -      2a03:b0c0:1:d0::6df:e001",
#        "A       matrix                  -         -       -      178.62.95.215",
#        "A       matrix                  -         -       -      2a03:b0c0:1:d0::6df:e001",
#        "CNAME   element                 -         -       -      matrix.fishbole.xyz",
#        "CNAME   jitsi                   -         -       -      matrix.fishbole.xyz",
#        "SRV     _matrix-identity._tcp   10        0       443    matrix.fishbole.xyz",
#        "-",
#        "Setting the IPv6 record is optional. If you need help doing this please contact us."

- name: Fetch 'server_vars.yml' from new server
  delegate_to: "{{ server_ip_final }}"
  fetch:
    src: "/matrix/awx/server_vars.yml"
    dest: "/tmp/{{ matrix_domain }}_new_server_vars.yml"
    flat: yes

- name: Include new server_vars.yml variable file
  include_vars: "/tmp/{{ matrix_domain }}_new_server_vars.yml"

- name:
  delegate_to: 127.0.0.1
  command: |
    perl -e 'print " " x (24 - length( '{{ awx_element_subdomain }}' ))';
  register: dns_spaces

- debug:
    msg: 
    - base_domain_used {{ base_domain_used }}
    - server_ipv4 {{ server_ipv4 }}
    - server_ipv6 {{ server_ipv6 }}
    - awx_element_subdomain {{ awx_element_subdomain }}
    
- debug:
    msg: 
    - Your server has been created! You now need to configure your DNS to have the 
    - "following records:"
    - Type    Host                    Priority  Weight  Port   Target
    - AAAA    matrix                  -         -       -      {{ server_ipv6 }}
    - CNAME   dimension               -         -       -      matrix.{{ matrix_domain }}
    - CNAME   {{ awx_element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
    - "-"
    - You also decided that your base domain was already in use, you'll need to configure
    - "a .well-known entry for your existing web service before you proceed:" 
    - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md
  when: base_domain_used|lower == 'true' and server_ipv4|length == 0 and server_ipv6|length > 0 

- debug:
    msg: 
    - Your server has been created! You now need to configure your DNS to have the 
    - "following records:"
    - Type    Host                    Priority  Weight  Port   Target
    - AAAA    -                       -         -       -      {{ server_ipv6 }}
    - AAAA    matrix                  -         -       -      {{ server_ipv6 }}
    - CNAME   dimension               -         -       -      matrix.{{ matrix_domain }}
    - CNAME   {{ awx_element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
  when: base_domain_used|lower == 'false' and server_ipv4|length == 0 and server_ipv6|length > 0

- debug:
    msg: 
    - Your server has been created! You now need to configure your DNS to have the 
    - "following records:"
    - Type    Host                    Priority  Weight  Port   Target
    - A       matrix                  -         -       -      {{ server_ipv4 }}
    - CNAME   dimension               -         -       -      matrix.{{ matrix_domain }}
    - CNAME   {{ awx_element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
    - "-"
    - You also decided that your base domain was already in use, you'll need to configure
    - "a .well-known entry for your existing web service before you proceed:" 
    - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md
  when: base_domain_used|lower == 'true' and server_ipv4|length > 0 and server_ipv6|length == 0 

- debug:
    msg: 
    - Your server has been created! You now need to configure your DNS to have the 
    - "following records:"
    - Type    Host                    Priority  Weight  Port   Target
    - A       -                       -         -       -      {{ server_ipv4 }}
    - A       matrix                  -         -       -      {{ server_ipv4 }}
    - CNAME   dimension               -         -       -      matrix.{{ matrix_domain }}
    - CNAME   {{ awx_element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
  when: base_domain_used|lower == 'false' and server_ipv4|length > 0 and server_ipv6|length == 0

- debug:
    msg: 
    - Your server has been created! You now need to configure your DNS to have the 
    - "following records:"
    - Type    Host                    Priority  Weight  Port   Target
    - A       matrix                  -         -       -      {{ server_ipv4 }}
    - AAAA    matrix                  -         -       -      {{ server_ipv6 }}
    - CNAME   dimension               -         -       -      matrix.{{ matrix_domain }}
    - CNAME   {{ awx_element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
    - "-"
    - You also decided that your base domain was already in use, you'll need to configure
    - "a .well-known entry for your existing web service before you proceed:" 
    - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md
  when: base_domain_used|lower == 'true' and server_ipv4|length > 0 and server_ipv6|length > 0 

- debug:
    msg: 
    - Your server has been created! You now need to configure your DNS to have the 
    - "following records:"
    - Type    Host                    Priority  Weight  Port   Target
    - A       -                       -         -       -      {{ server_ipv4 }}
    - AAAA    -                       -         -       -      {{ server_ipv6 }}
    - A       matrix                  -         -       -      {{ server_ipv4 }}
    - AAAA    matrix                  -         -       -      {{ server_ipv6 }}
    - CNAME   dimension               -         -       -      matrix.{{ matrix_domain }}
    - CNAME   {{ awx_element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
  when: base_domain_used|lower == 'false' and server_ipv4|length > 0 and server_ipv6|length > 0
