
# Create AWX token for executing modules
- import_tasks: "{{ role_path }}/tasks/create_token.yml"
  when: not view_borg_backup | bool
  
# Backup original subscription if possible and stop the service
- import_tasks: "{{ role_path }}/tasks/backup_server.yml"
  when: not view_borg_backup | bool

# Restore the latest backup to the backup servers extraction directory
- import_tasks: "{{ role_path }}/tasks/restore_backup.yml"

# Create a new subscription for the recovered server
- import_tasks: "{{ role_path }}/tasks/create_subscription.yml"

# Provision the new server with the same settings
- import_tasks: "{{ role_path }}/tasks/provision_server.yml"

# Deploy the server without letsencrypt renewal
- import_tasks: "{{ role_path }}/tasks/deploy_service.yml"

# Rsync the backup from the backup server to the recovered server
- import_tasks: "{{ role_path }}/tasks/transmit_backup.yml"

# Import the database dump to the recovered server
- import_tasks: "{{ role_path }}/tasks/import_database.yml"

# Reprovision the new server to populate the surveys
- import_tasks: "{{ role_path }}/tasks/re-provision_server.yml"

# Delete AWX token for executing modules
- import_tasks: "{{ role_path }}/tasks/delete_token.yml"

# Print DNS advice
- import_tasks: "{{ role_path }}/tasks/dns_advice.yml"
