
- name: "Upgrades a host from Debian 10 to Debian 11."
  hosts: matrix_clients, wireguard_clients
  gather_facts: true

  tasks:
### install python3-apt package, see: https://gitlab.com/GoMatrixHosting/matrix-docker-ansible-deploy/-/issues/7#note_721667716

#- name: Install necessary packages
#  apt:
#    pkg:
#    - python3-apt

# 1 - Backup the system.

# 2 - Update existing packages and reboot the Debian 10 system.

    - name: Update all packages to their latest version
      apt:
        update_cache: yes

    - name: Upgrade all packages to their latest version
      apt:
        name: "*"
        state: latest

# 3 - Edit the file /etc/apt/sources.list using a text editor and replace each instance of 'buster' with 'bullseye'. 

# 4 - Next find the security line, replace keyword 'buster/updates' with 'bullseye-security'.
# ```
# deb http://deb.debian.org/debian/ bullseye main
# deb http://deb.debian.org/debian/ bullseye-updates main
# deb http://security.debian.org/debian-security bullseye-security main
# ```

    - name: Template a file to /etc/apt/sources.list
      template:
        src: "./templates/bullseye_sources.list"
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'

# 5 - Update the packages index on Debian Linux, run:
#     `sudo apt update`
# ```
# - name: Update all packages to their latest version
#   apt:
#     update_cache: yes
# ```

    - name: Update all packages to their latest version
      apt:
        update_cache: yes

#6 - Prepare for the operating system upgrade, run:
#    `sudo apt upgrade`
# ```
# - name: Upgrade all packages to their latest version
#   apt:
#     name: "*"
#     state: latest
# ```

    - name: Upgrade all packages to their latest version
      apt:
        name: "*"
        state: latest

# 7 - Finally, update Debian 10 to Debian 11 bullseye by running:
#    `sudo apt full-upgrade`
# ```
# - name: Upgrade the OS (apt-get dist-upgrade)
#   apt:
#     upgrade: dist/full?
# ```

    - name: Upgrade to Debian 11 (apt-get dist-upgrade)
      apt:
        upgrade: full

# 8 - Reboot the Linux system so that you can boot into Debian 11 Bullseye

#- name: Reboot the server to completely apply the upgrade
#  reboot:
#    reboot_timeout: 600

    - name: restart server
      shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
      async: 1
      poll: 0
      become: true

#- name: Wait for server to restart
#  local_action:
#    module: wait_for
#      host={{ ansible_ssh_host }}
#      port=22
#      delay=10
#    become: false

# 9 - Verify that everything is working correctly.
